{% set name = "erlab" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/erlab-{{ version }}.tar.gz
  sha256: 04d35d0b903d90050774a73ff816d0244cb10dc38cc196361aa8ab7a19cf7108

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools >=61
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=3.11
    - h5netcdf >=1.2.0
    - igor2 >=0.5.6
    - joblib >=1.3.2
    - lmfit >=1.2.0,!=1.3.0
    - matplotlib-base >=3.8.0
    - numba >=0.59.0
    - numbagg >=0.8.1
    - numpy >=1.26.0
    - pyperclip >=1.8.2
    - pyqtgraph >=0.13.1
    - qtawesome >=1.3.1
    - qtpy >=2.4.1
    - scipy >=1.12.0
    - tqdm >=4.66.2
    - uncertainties >=3.1.4
    - varname >=0.13.0
    - xarray >=2024.02.0
  run_constrained:
    - pyside2 >=5.15
    - pyqt >=5.15
    - iminuit >=2.25.2

test:
  imports:
    - erlab
    - erlab.io
    - erlab.plotting
    - erlab.analysis
  commands:
    - pip check
  requires:
    - pyqt >=5.15
    - pip

about:
  home: https://github.com/kmnhan/erlabpy
  summary: Python package for ARPES data analysis and visualization.
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://erlabpy.readthedocs.io/
  dev_url: https://github.com/kmnhan/erlabpy

extra:
  recipe-maintainers:
    - kmnhan
  feedstock-name: erlabpy
